services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    #ports:
    #  - "8080:8080"
    networks:
      - termix_internal
      - caddy-1_caddy_net
    volumes:
      - type: volume
        source: termix_data
        target: /app/data
        volume: {}
    environment:
      PORT: "8080"

volumes:
  termix_data:
      name: termix_termix_data
      driver_opts:
        type: "nfs"
        o: ${TERMIX_NFS_PATH}
        device: ${TERMIX_NFS_DEVICE_DATA}

networks:
  termix_internal:
  caddy-1_caddy_net:
    external: true
